tap "derailed/k9s"
# Static checker for GitHub Actions workflow files
brew "actionlint"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Tool for exploring each layer in a docker image
brew "dive"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Task is a task runner/build tool that aims to be simpler and easier to use
brew "go-task"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Kubernetes package manager
brew "helm"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Run local Kubernetes cluster in Docker
brew "kind"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Terminal file manager
brew "lf"
# Package manager for the Lua programming language
brew "luarocks"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "derailed/k9s/k9s", trusted: true
# GPU-accelerated terminal emulator
cask "alacritty"
# Terminal-based AI coding assistant
cask "claude-code"
# UI to create reproducible developer environments based on a devcontainer.json
cask "devpod"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
# Web browser
cask "google-chrome"
# Graphical client for Git version control
cask "sourcetree"
# Open-source code editor
cask "visual-studio-code"
